name: storm-tracking
channels:
  - conda-forge
dependencies:
  - python=3.10
  - cartopy
  - dask
  - esmpy=8.4.2
  - jupyter-book
  - jupyterlab
  - libjpeg-turbo 
  - libtiff=4.5.0
  - matplotlib=3.7.1
  - mystmd
  - netcdf4
  - numpy
  - pandas
  - pathlib
  - pillow=9.4.0
  - tobac
  - xarray
  - xesmf
  